/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUnitsRouteImport } from './routes/app.units'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRentalsRouteImport } from './routes/app.rentals'
import { Route as AppRemindersRouteImport } from './routes/app.reminders'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppCustomersRouteImport } from './routes/app.customers'

const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRentalsRoute = AppRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff-login': typeof StaffLoginRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/rentals': typeof AppRentalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/units': typeof AppUnitsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff-login': typeof StaffLoginRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/rentals': typeof AppRentalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/units': typeof AppUnitsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff-login': typeof StaffLoginRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/rentals': typeof AppRentalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/units': typeof AppUnitsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/portal'
    | '/reset-password'
    | '/staff-login'
    | '/app/customers'
    | '/app/documents'
    | '/app/payments'
    | '/app/reminders'
    | '/app/rentals'
    | '/app/settings'
    | '/app/units'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/reset-password'
    | '/staff-login'
    | '/app/customers'
    | '/app/documents'
    | '/app/payments'
    | '/app/reminders'
    | '/app/rentals'
    | '/app/settings'
    | '/app/units'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/portal'
    | '/reset-password'
    | '/staff-login'
    | '/app/customers'
    | '/app/documents'
    | '/app/payments'
    | '/app/reminders'
    | '/app/rentals'
    | '/app/settings'
    | '/app/units'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StaffLoginRoute: typeof StaffLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/units': {
      id: '/app/units'
      path: '/units'
      fullPath: '/app/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rentals': {
      id: '/app/rentals'
      path: '/rentals'
      fullPath: '/app/rentals'
      preLoaderRoute: typeof AppRentalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reminders': {
      id: '/app/reminders'
      path: '/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppRentalsRoute: typeof AppRentalsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppRentalsRoute: AppRentalsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StaffLoginRoute: StaffLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
